### ISSUE TITLE
What is the unit of wind data in "GriddedDailyClimateData2009-2019.csv" in OSF

### ISSUE THREAD

**Issue by huitang-earth** [Between-the-Fjords/seedclim-data#29]
@audhalbritter 

I am trying to plot the climate data from "GriddedDailyClimateData2009-2019.csv".  While precipitation and temperature look well, I am a bit confused with what kind of unit is used for wind data. The standard unit for wind speed should be "m/s" (meter per second). But when I assume this unit, the wind speed appear to be very large.

**Comment by audhalbritter** [comment]
Hi Hui,

The units for the gridded climate data are as follows:
Climate variables are
- Mean daily temperature (°C, Temperature)
- Relative air moisture (%, RelAirMoisture)
- Mean wind (meter / second, Wind)
- Mean cloud cover (in 8 parts, no dimension, CloudCover)
- Precipitation (mm, Precipitation)

Wind is measured in m/s. We will add this to the data in the next version!
