### ISSUE TITLE
inconsistent use of siteID in temperature and precipitation in SeedClim data

### ISSUE THREAD

**Issue by huitang-earth** [Between-the-Fjords/seedclim-data#31]
Some siteID used in **Precipitation.zip**, **Temperature.zip** and **SoilMoisture.zip** from "8_Environmental_data" are different from that used in other data files.

More specifically:    

**Ulvhaugen** has been used instead of **Ulvehaugen**
**Skjellingahaugen** has been used instead of **Skjelingahaugen**

This cause some troubles when reading and processing the data.

**Comment by audhalbritter** [comment]
Oh yes, we know about that problem, but I thought we had fixed it. I'll check it again!

**Comment by audhalbritter** [comment]
The siteID in these files should be fixed now.
